containerd/containerd.io

LICENSE
Update to proper license for docs/website.
=> Update license to CC-BY-4.0 for docs/website

.travis.yml
=> Add DCO check to website repo

config.toml
=> Update to latest release(s)

layouts/index.html
containerd is now a graduated maturity project in the CNCF.
=> Update project status to graduated

config.toml
Closes: #37 
We have a new release since PR 37 was opened.
=> Update to latest release (1.2.7)

content/releases.md
This file does not sync automatically. We might want to consider a way to keep the website updated from the other repos, but for now this brings it up to date.
=> Update releases doc

config.toml
=> Update latest release to 1.3.0

layouts/index.html
Signed-off-by: surya474 <gantasuryateja474@gmail.com>
=> Added alt tags for images in home page

.github/workflows/sync-releases.yml
=> Add a signed-off-by to auto-PR so CI passes

config.toml
=> Update latest release to 1.3.2

.gitignore, .htmltest.yml, Makefile, README.md, assets/sass/style.sass, content/releases.md, layouts/docs/list.html, layouts/docs/single.html, layouts/partials/docs/dropdown.html, layouts/partials/docs/tabs.html, layouts/partials/footer.html, layouts/partials/meta.html, layouts/partials/navbar.html, netlify.toml
This PR adds a link checker to the site build and fixes existing broken links.
cc @estesp
=> Add link checker

.github/workflows/sync-releases.yml
Should fix incorrect bot-generated PRs like #56 
=> Fixup whitespace error generated by sed replacement

config.toml
https://containerd.io/downloads/ is a bit stale
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
=> Update latest release to 1.3.3

.github/workflows/ci.yml
=> Add timeout for CI actions

layouts/partials/footer.html
This PR updates the footer text of containerd.io to bring it in compliance with Linux Foundation standards.
=> Update footer text

config.toml
=> Update to latest 1.3.6 release

config.toml
v1.4.1 is the most recent release
=> Update latest version to 1.4.1

config.toml
=> Update latest release

.github/workflows/ci.yml, config.toml
=> Update to 1.5.0 as latest release

config.toml, layouts/shortcodes/releases.html
=> Update latest to 1.5.2

config.toml, content/docs/getting-started.md
Signed-off-by: Sunny Goel <sunnygoel1987@gmail.com>
=> Updated config.toml and getting-started.md files to reflect latest config version (version=2)

content/docs/getting-started.md
=> Update Go version requirements

config.toml
=> Add latest release 1.6.1

assets/js/jquery-3.6.0.js, config.toml
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
=> Upgrade jQuery from 3.3.1 to 3.6.0

config.toml
=> Update to latest release 1.6.4

.github/workflows/ci.yml, config.toml
Update latest release to 1.6.8 on containerd.io
=> Update latest release to 1.6.8

config.toml
Signed-off-by: Mohamed Zaian <mohamedzaian@gmail.com>
Update latest release to 1.6.9 on containerd.io
=> Update latest release to 1.6.9

config.toml
=> Update to latest release

config.toml
Signed-off-by: Mohamed Zaian <mohamedzaian@gmail.com>
=> Update latest release to 1.6.12

config.toml
Signed-off-by: Mohamed Zaian <mohamedzaian@gmail.com>
=> Update latest release to 1.6.14

config.toml, content/downloads/_index.md
Also try and force the downloads page to re-render in Hugo.
=> Update to latest version 1.6.15

config.toml
=> Update to latest containerd release

config.toml
Signed-off-by: Mohamed Zaian [mohamedzaian@gmail.com](mailto:mohamedzaian@gmail.com)
=> Update latest release to 1.6.18

config.toml
Signed-off-by: Mohamed Zaian [mohamedzaian@gmail.com](mailto:mohamedzaian@gmail.com)
=> Update latest release to 1.6.19

config.toml, content/releases.md
=> Update config for 1.7.2 release 

.github/workflows/ci.yml, .github/workflows/sync-releases.yml
- actions/checkout@v4
- peter-evans/create-pull-request@v7
=> update github actions

config.toml
=> Update latest to 2.0.0
