containerd/containerd.io

Makefile, README.md
This PR adds additional instructions on running the site locally, how it's published, and how to contribute new docs.
Apologies to @estesp, but I believe this eliminates the need for PR #5.
=> Add metadocumentation to the README

.gitignore, config.toml, layouts/partials/meta.html
This PR adds some basic SEO stuff for Facebook's OpenGraph and Twitter Cards. This will be essential to search engine discoverability.
=> Add OpenGraph and Twitter Card metadata to HTML head

config.toml
This PR encompasses a small handful of config updates for the site:
* Sets the `baseURL`, which will make the sitemap render correctly
* Enables the addition of a [`robots.txt`](https://deploy-preview-13--containerd-io.netlify.com/robots.txt) to the site
* Disables the creation of content taxonomies (we may use these later but for now they just generate unused files)
=> Site configuration update

data/repos.yaml
Hi
The repo name for containerd seems to be bad on https://containerd.io/docs/
Cheers
=> Replace repo name for containerd

config.toml
The copyright year is a var in the footer partial, but need a Hugo
run/deploy to get it updated to 2019. Also, latest release is now
containerd 1.2.1
=> Update copyright year and latest release

layouts/partials/navbar.html
This PR adds a link to the new CNCF project branding site: https://branding.cncf.io/projects/containerd/
=> Add link to containerd project branding page

.github/workflows/sync-releases.yml
runs a daily cron job and on any instance in which there are changes, will create a PR to automatically sync the differences.
Fixes: #46
=> Create GitHub Action to sync RELEASES.md

.github/workflows/sync-releases.yml
This could become brittle, but for now seems like a reasonable quick fix
to not have dead links in the copied-in releases.md from the main
containerd repository.
// cc: @lucperkins per discussion in #53 
=> Remove invalid links when copying in markdown

.github/workflows/ci.yml
For this repository the only thing we had was a DCO check running in
Travis. This moves this step to run as a GitHub Action.
=> Switch to GitHub actions for CI

config.toml, content/downloads/_index.md
Also update the wget command to use the correct filename format
generated by the new GitHub Actions release step.
=> Update latest release to v1.3.5

.github/workflows/ci.yml, Makefile
Use pre-baked project checks to solve existing GH action's use of
deprecated env setting method.
=> Fix GitHub Actions script

content/releases.md, data/repos.yaml
Reflecting in the docs that CRI is now merged.. 
Also since we had a statement about kubelet only supporting 1 version of CRI .. I felt we needed to update that to describe the change to v1.21 of kubelet.
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
=> updating the CRI description

layouts/shortcodes/releases.html
Let's only show the last 50 releases as we really don't need to show 100
of them, with many of them being out of service/very old. Also, adding
the page number seems to have fixed the problem that it wasn't showing
the very latest releases? Or maybe it was a cache issue? We'll know next
time we update a release :)
=> Fix release query to get latest releases

config.toml, content/releases.md
for https://github.com/containerd/containerd/releases/tag/v1.6.0
=> Update releases for v1.6.0

content/docs/getting-started.md
This PR syncs the Getting started section on containerd.io with the documentation in the containerd/containerd repository.
=> Sync getting-started with docs of main containerd repo

.github/workflows/sync-releases.yml
The peter-evans/create-pull-request@v2 action has stopped working due to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/. Migrate to v4 which addresses the break.
(I triggered a manual run through `workflow_dispatch` which generated https://github.com/samuelkarp/containerd.io/pull/1 in case you want to see it work.)
=> workflows: update sync-releases

content/docs/_index.md
It doesn't make much sense to retain "Check back soon" for more than four years.
=> Remove "Check back soon"

config.toml
Currently the downloads list on the website is only re-generated if Hugo can't find a cache of the page in Netlify, which seems to persist for {a long time} unless a change is made to the downloads page itself.
Setting the cache to 24 hours for the "getJSON" call so that each time we update the release it should force a re-render of the downloads list.
=> Force release JSON to update each time we update the site

netlify.toml
We don't need particular features/fixes, but asking others to install Hugo from 2022 doesn't make much sense.
=> Upgrade Hugo from 0.65.3 to 0.111.3

README.md
ran into this issue when getting started:
```
ERROR TOCSS: failed to transform "sass/style.sass" (text/x-sass): "/Users/haddscot/workplace/containerd.io/themes/containerd/assets/sass/style.sass:10:1": File to import not found or unreadable: bulma/sass/utilities/initial-variables.
```
spent a little more time than I would have liked figuring out that I needed to `npm install .`
hopefully this saves the next guy a little bit of time
=> add npm install . to README instructions

.github/workflows/sync-releases.yml
Substitute the relative links (relative to the containerd repo) with absolute links that point at the main branch of the containerd repo.
=> Fix relative links for containerd docs

content/keps.md
This adds public documentation of the process for containerd project collaboration with Kubernetes SIG-Node.  It is mostly a formalization of what we have already been doing informally, but the formalization should help with visibility and work distribution.
=> Add process for SIG-Node collaboration

content/keps.md
This small PR fixes the `kubernetes/enhancements` reference. Relevant page: https://containerd.io/keps/
=> Fix Kubernetes enhancements repo
